name: Deploy (prod)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      APP_ROOT: /var/www/amp.lucashussey.com
      RELEASE_PATH: /var/www/amp.lucashussey.com/releases/${{ github.sha }}
      CURRENT_PATH: /var/www/amp.lucashussey.com/current
      WEB_DIST: /var/www/amp.lucashussey.com/html

    steps:
      # Step 1: Setup
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.0"
          cache: "pnpm"

      # Step 2: Install dependencies and build
      - name: Install Server Dependencies
        run: pnpm --filter apps/server install

      - name: Install Shared Dependencies
        run: pnpm --filter packages/shared install

      - name: Install Web Dependencies
        run: pnpm --filter apps/web install

      - name: Build Server
        run: pnpm --filter apps/server run build

      - name: Build Shared
        run: pnpm --filter packages/shared run build

      - name: Build React App
        run: pnpm --filter apps/web run build

      # Step 3: Deploy the built server files to Oracle Cloud VM via SSH/rsync
      - name: Deploy to Oracle Instance via rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "." # Change to "build/" if you use Create React App
          REMOTE_HOST: ${{ secrets.OCI_HOST }}
          REMOTE_USER: ${{ secrets.OCI_USERNAME }}
          TARGET: "/var/www/amp.lucashussey.com/repo" # The root directory of your node server on the VM

      # Step 4: Deploy the built web files to Oracle Cloud VM via SSH/rsync
      - name: Deploy to Oracle Instance via rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "apps/web/dist/" # Change to "build/" if you use Create React App
          REMOTE_HOST: ${{ secrets.OCI_HOST }}
          REMOTE_USER: ${{ secrets.OCI_USERNAME }}
          TARGET: "/var/www/amp.lucashussey.com/html" # The root directory of your web server on the VM
